Update aquasec.yml

diff --git a/.github/workflows/aquasec.yml b/.github/workflows/aquasec.yml
--- a/.github/workflows/aquasec.yml
+++ b/.github/workflows/aquasec.yml
@@ -19,30 +19,85 @@ jobs:
         with:
           username: ${{ secrets.DOCKERHUB_USERNAME }}
           password: ${{ secrets.DOCKERHUB_PASSWORD }}
-      - name: Run Trivy vulnerability scanner - FS mode
-        uses: aquasecurity/trivy-action@0.5.1
+      - name: Run Aqua scanner
+        uses: docker://aquasec/aqua-scanner
         with:
-          scan-type: 'fs'
-          security-checks: 'vuln,config,secret'
-          hide-progress: false
-          format: 'table'
+          args: trivy fs --security-checks config,vuln,secret --sast .
+          # To customize which severities to scan for, add the following flag: --severity UNKNOWN,LOW,MEDIUM,HIGH,CRITICAL
+          # To enable SAST scanning, add: --sast
+          # To enable npm/dotnet non-lock file scanning, add: --package-json / --dotnet-proj
         env:
           AQUA_KEY: ${{ secrets.AQUA_KEY }}
           AQUA_SECRET: ${{ secrets.AQUA_SECRET }}
-          TRIVY_RUN_AS_PLUGIN: 'aqua'
-          TRIGGERED_BY: 'PUSH'
           GITHUB_TOKEN: ${{ github.token }}
-      - name: Build and push
-        uses: docker/build-push-action@v3
+          TRIVY_RUN_AS_PLUGIN: 'aqua'
+      #- name: Run Trivy vulnerability scanner - FS mode
+        #uses: aquasecurity/trivy-action@0.5.1
+        #with:
+          #scan-type: 'fs'
+          #security-checks: 'vuln,config,secret'
+          #hide-progress: false
+          #format: 'table'
+        #env:
+          #AQUA_KEY: ${{ secrets.AQUA_KEY }}
+          #AQUA_SECRET: ${{ secrets.AQUA_SECRET }}
+          #TRIVY_RUN_AS_PLUGIN: 'aqua'
+          #TRIGGERED_BY: 'PUSH'
+          #GITHUB_TOKEN: ${{ github.token }}
+      # Runs docker build 
+      - name: Build docker image
+        run: sudo docker build -t aquasaemea/insecure-bank-app:${{ github.sha }} .
+      
+      # Aqua Registry login
+      - name: Login to Aqua Registry
+        uses: docker/login-action@v1
         with:
-          push: true
-          tags: "aquasaemea/insecure-bank-app:${{ github.sha }}"
-      - name: Manifest Generation
+          registry: registry.aquasec.com
+          username: ${{ secrets.AQUADEV_USERNAME }}
+          password: ${{ secrets.AQUADEV_PASS }}
+          
+      #- name: Build and push
+        #uses: docker/build-push-action@v3
+        #with:
+          #push: true
+          #tags: "aquasaemea/insecure-bank-app:${{ github.sha }}"
+          
+      # Scan the Image
+      - name: Run the scanner 
         run: |
-          docker image ls
-          curl -L ${{ secrets.BILLY_URL }}/v1/api/download/sh | sh
-          billy generate \
-              --access-token "${{ secrets.GITHUB_TOKEN }}" \
-             --aqua-key "${{ secrets.AQUA_KEY }}" \
-             --aqua-secret "${{ secrets.AQUA_SECRET }}" \
-             --artifact-path "aquasaemea/insecure-bank-app:${{ github.sha }}"
+          docker run --rm -v /var/run/docker.sock:/var/run/docker.sock registry.aquasec.com/scanner:2022.4 scan --host ${{ secrets.AQUA_HOST }} --local aquasaemea/insecure-bank-app:${{ github.sha }} --token ${{ secrets.AQUA_TOKEN }} --layer-vulnerabilities --no-verify --html > .github/workflows/scan-output.html
+      
+      # Runs docker push 
+      - name: Build docker image
+        run: sudo docker push aquasupportemea/insecure-bank-app:${{ github.sha }} . 
+      
+      - name: SBOM Generation
+        run: |
+          #export BILLY_SERVER=https://billy.codesec.aquasec.com
+          curl -sLo install.sh download.codesec.aquasec.com/billy/install.sh
+          curl -sLo install.sh.checksum https://github.com/argonsecurity/releases/releases/latest/download/install.sh.checksum
+          if ! cat install.sh.checksum | sha256sum ; then
+          echo "install.sh checksum failed"
+          exit 1
+          fi
+          BINDIR="." sh install.sh
+          rm install.sh install.sh.checksum
+          ./billy generate \
+            --access-token "${{ github.token }}" \
+            --aqua-key "${{ secrets.AQUA_KEY }}" \
+            --aqua-secret "${{ secrets.AQUA_SECRET }}" \
+            --artifact-path "aquasaemea/insecure-bank-app:${{ github.sha }}"
+            
+            # The docker image name:tag of the newly built image
+            # --artifact-path "my-image-name:${{ env.tag-version }}" 
+            # OR the path to the root folder of your project. I.e my-repo/my-app 
+            # --artifact-path "${{env.MY_APP_ROOT}}"
+      #- name: Manifest Generation
+        #run: |
+          #docker image ls
+          #curl -L ${{ secrets.BILLY_URL }}/v1/api/download/sh | sh
+          #billy generate \
+             #--access-token "${{ secrets.GITHUB_TOKEN }}" \
+             #--aqua-key "${{ secrets.AQUA_KEY }}" \
+             #--aqua-secret "${{ secrets.AQUA_SECRET }}" \
+             #--artifact-path "aquasaemea/insecure-bank-app:${{ github.sha }}"
